create table public.fantasy_teams (id uuid primary key default gen_random_uuid(), manager_name text not null unique, team_name text);
create table public.weeks (id uuid primary key default gen_random_uuid(), number integer not null unique, label text, is_published boolean not null default false);
create table public.players (id uuid primary key default gen_random_uuid(), name text not null unique, role text not null check (role in ('star','pro','troupe','hough','judges_hosts','surprise_pro')), status text not null default 'active' check (status in ('active','eliminated')), appearance_rate integer not null default 0);
create table public.partnerships (id uuid primary key default gen_random_uuid(), star_id uuid unique references public.players(id), pro_id uuid unique references public.players(id), active boolean not null default true);
create table public.roster_history (id uuid primary key default gen_random_uuid(), player_id uuid not null references public.players(id), fantasy_team_id uuid references public.fantasy_teams(id), starts_week_id uuid references public.weeks(id), ends_week_id uuid references public.weeks(id));
create table public.score_events (id uuid primary key default gen_random_uuid(), week_id uuid not null references public.weeks(id), player_id uuid not null references public.players(id), kind text not null check (kind in ('official','appearance')), points integer not null check (points >= 0), label text, created_at timestamptz not null default now());
alter table public.fantasy_teams enable row level security; alter table public.weeks enable row level security; alter table public.players enable row level security; alter table public.partnerships enable row level security; alter table public.roster_history enable row level security; alter table public.score_events enable row level security;
create policy "public read teams" on public.fantasy_teams for select using (true); create policy "public read weeks" on public.weeks for select using (true); create policy "public read players" on public.players for select using (true); create policy "public read partnerships" on public.partnerships for select using (true); create policy "public read rosters" on public.roster_history for select using (true); create policy "public read scores" on public.score_events for select using (true);
-- Add commissioner write policies after you choose the commissioner email. Do not enable public writes.
