import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';
const supabase=createClient('https://mdrrnanxqazecqviaass.supabase.co','sb_publishable_ylMIgpLXA0NBoeb3aPI8qQ_m0wrG7It');const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let session=null;async function load(){const {data}=await supabase.auth.getSession();session=data.session;$('#auth').textContent=session?'Commissioner signed in':'Public view';const {data:weeks}=await supabase.from('weeks').select('*').order('number');$('#week').innerHTML=(weeks||[]).map(w=>`<option value="${w.id}">Week ${w.number}${w.label?' · '+w.label:''}</option>`).join('')||'<option>Create a week in Roster manager</option>';teams();roster();score()}
function page(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id))}$$('nav button').forEach(b=>b.onclick=()=>page(b.dataset.view));
async function teams(){const {data}=await supabase.from('fantasy_teams').select('*').order('manager_name');$('#teams').innerHTML=(data||[]).map(t=>`<div class="row"><span><b>${t.manager_name}</b><small>${t.team_name||'No fantasy team name'}</small></span></div>`).join('')||'<p class="sub">No fantasy teams yet.</p>'}
async function roster(){const q=$('#rosterSearch').value||'';const {data}=await supabase.from('players').select('*').ilike('name',`%${q}%`).order('name');$('#rosterResults').innerHTML=(data||[]).map(p=>`<div class="row"><span><b>${p.name}</b><small>${p.role} · ${p.status}</small></span><button data-player="${p.id}">Edit</button></div>`).join('')||'<p class="sub">No players yet. Add your real draft pool manually.</p>';$$('[data-player]').forEach(b=>b.onclick=()=>editPlayer(b.dataset.player))}
async function score(){const q=$('#scoreSearch').value||'';const {data}=await supabase.from('players').select('*').eq('status','active').ilike('name',`%${q}%`).order('name');$('#scoreResults').innerHTML=(data||[]).map(p=>`<div class="row"><span><b>${p.name}</b><small>${p.role}</small></span><button data-score="${p.id}">Score</button></div>`).join('')||'<p class="sub">No active players yet. Add your player pool in Roster manager.</p>';$$('[data-score]').forEach(b=>b.onclick=()=>scorePlayer(b.dataset.score))}
function modal(html){$('#modalBody').innerHTML=html;$('#modal').showModal()}async function editPlayer(id){const {data:p}=await supabase.from('players').select('*').eq('id',id).single();modal(`<div class="modal"><h2>${p.name}</h2><label>Role<select id="role"><option ${p.role==='star'?'selected':''}>star</option><option ${p.role==='pro'?'selected':''}>pro</option><option ${p.role==='troupe'?'selected':''}>troupe</option><option>hough</option><option>judges_hosts</option><option>surprise_pro</option></select></label><label>Status<select id="status"><option ${p.status==='active'?'selected':''}>active</option><option ${p.status==='eliminated'?'selected':''}>eliminated</option></select></label><button id="savePlayer">Save player</button><p class="sub">Final behavior: changing an active partnership to eliminated will update both people and keep their past score history.</p></div>`);$('#savePlayer').onclick=async()=>{await supabase.from('players').update({role:$('#role').value,status:$('#status').value}).eq('id',id);$('#modal').close();load()}}
async function scorePlayer(id){const {data:p}=await supabase.from('players').select('*').eq('id',id).single();modal(`<div class="modal"><h2>${p.name}</h2><label>Score type<select id="kind"><option value="official">Official judges’ points</option><option value="appearance">Dance appearance</option></select></label><label>Points<input id="points" type="number" min="0"></label><label>Optional label<input id="label" placeholder="Opening number"></label><button id="saveScore">Save score event</button></div>`);$('#saveScore').onclick=async()=>{await supabase.from('score_events').insert({week_id:$('#week').value,player_id:id,kind:$('#kind').value,points:+$('#points').value,label:$('#label').value||null});$('#modal').close();load()}}
$('#rosterSearch').oninput=roster;$('#scoreSearch').oninput=score;$('#newPlayer')?.addEventListener('click',()=>{modal(`<div class="modal"><h2>Add a player manually</h2><p class="sub">Use the image filename exactly as it appears in the Images folder.</p><label>Name<input id="newName" placeholder="Player name"></label><label>Role<select id="newRole"><option value="star">Star</option><option value="pro">Pro</option><option value="troupe">Troupe</option><option value="hough">Hough</option><option value="judges_hosts">Judges + Hosts</option><option value="surprise_pro">Surprise Pro</option></select></label><label>Appearance rate<input id="newRate" type="number" value="0"></label><label>Image filename<input id="newImage" placeholder="Maura Higgins.jpg"></label><button id="createPlayer">Create player</button></div>`);$('#createPlayer').onclick=async()=>{const {error}=await supabase.from('players').insert({name:$('#newName').value,role:$('#newRole').value,appearance_rate:+$('#newRate').value,image_path:$('#newImage').value?`Images/${$('#newImage').value}`:null});if(error)return alert(error.message);$('#modal').close();load()}});$('#magic').onclick=async()=>{const email=$('#email').value;const {error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:'https://fkherb.github.io/mirrorball-fantasy-league/'}});alert(error?error.message:'Check your email for the sign-in link.')};load();
