// Completed leagues share these view templates. Callers adapt their league-scoped
// database records into the same view models and keep their own action handlers.
const html = (value = '') => String(value ?? '').replace(/[&<>"']/g, (char) => ({
  '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
})[char]);
const imagePosition = (value) => value != null && Number.isFinite(Number(value)) ? Number(value) : 50;

export function standingCard({ id, rank, manager, name, contributors, total, selected, leader, tied }) {
  return `<article class="card standing-card ${leader || tied ? 'leader' : ''} ${tied ? 'tied-leader' : ''} ${selected ? 'selected' : ''}" data-standing-team="${html(id)}" tabindex="0" role="button" aria-label="View ${html(name)} score breakdown"><div class="standing-rank">${rank}</div><div class="standing-main"><p class="eyebrow">${html(manager)}</p><h2>${html(name)}</h2>${tied ? '<p class="tie-note">Tied for first</p>' : ''}<div class="standing-contributors">${contributors.slice(0, 4).map(({ name: castName, points }) => `<span>${html(castName)} <b>${points}</b></span>`).join('') || '<span>No cast assigned</span>'}${contributors.length > 4 ? `<span>+${contributors.length - 4} more</span>` : ''}</div></div><div class="standing-total"><strong>${total}</strong><span>points</span></div><span class="card-chevron standing-chevron" aria-hidden="true">›</span></article>`;
}

export function scoreRows(rows, { limit = null, withImages = false, imageFor = () => '', historicalJudges = false } = {}) {
  return `<div class="league-score-list">${(limit ? rows.slice(0, limit) : rows).map((row) => {
    const member = row.member;
    const hasJudges = ['Star', 'Pro'].includes(row.role) || (historicalJudges && ['Eliminated Star', 'Eliminated Pro'].includes(row.role));
    return `<div class="league-score-row ${withImages ? 'with-photo' : ''}" data-score-cast-detail="${html(member.id)}" tabindex="0" role="button">${withImages ? `<img class="score-member-photo" src="${html(imageFor(member))}" style="object-position:${imagePosition(member.image_position)}% center" alt="">` : ''}<div class="league-score-member"><strong>${html(member.name)}</strong><span class="role-rate-pill">${html(row.displayRole || row.role)} <b>+${Number(row.appearanceRate) || 0}</b></span></div><div class="league-score-parts">${hasJudges ? `<span>Judges Total <b>${row.official || 0}</b></span>` : ''}<span class="appearance-part">Appearances <b>${row.appearances || 0}</b></span></div><strong class="league-score-total">${row.total || 0}</strong></div>`;
  }).join('') || '<p class="sub league-empty">No points recorded in this view.</p>'}</div>`;
}

export function overviewTeamDetail({ name, manager, total, castRows }) {
  return `<div class="league-detail-head"><div><p class="eyebrow">Selected team</p><h2>${html(name)}</h2><p class="sub">Managed by ${html(manager)}</p></div><div class="league-detail-total"><strong>${total}</strong><span>season points</span></div></div><p class="top-cast-label">Top Five Cast Members</p>${scoreRows(castRows, { limit: 5, historicalJudges: true })}`;
}

export function highlightCards({ teamScore, teamNames, castScore, castNames, appearances, appearanceNames,
  teamNamesHtml, castNamesHtml, appearanceNamesHtml }) {
  const names = (items) => `<div class="highlight-name-list">${items.map((name) => `<span>${html(name)}</span>`).join('')}</div>`;
  return `<article class="card"><small>Team of the week</small>${teamScore ? `<strong class="highlight-value">${teamScore}</strong><p>fantasy points${teamNames.length > 1 ? ' each' : ''}</p>${teamNamesHtml || names(teamNames)}` : '<p>No fantasy-team points were recorded.</p>'}</article><article class="card"><small>Top cast score</small>${castScore ? `<strong class="highlight-value">${castScore}</strong><p>points${castNames.length > 1 ? ' each' : ''}</p>${castNamesHtml || names(castNames)}` : '<p>No cast points were recorded.</p>'}</article><article class="card"><small>Most appearances</small>${appearances ? `<strong class="highlight-value">${appearances}</strong><p>dance${appearances === 1 ? '' : 's'}${appearanceNames.length > 1 ? ' each' : ''}</p>${appearanceNamesHtml || names(appearanceNames)}` : '<p>No appearances were recorded.</p>'}</article>`;
}

export function teamCard({ id, manager, name, roster, editButton = false, emptyMessage = 'No cast members assigned yet.', footerHtml = '' }) {
  return `<article class="card team-card" data-team-card-id="${html(id)}" data-team-detail="${html(id)}" tabindex="0" role="button" aria-label="View ${html(name)} cast roster"><div class="team-card-head"><div><p class="eyebrow">${html(manager)}</p><h2>${html(name)}</h2></div>${editButton ? `<button class="secondary team-edit-button" data-edit-team-id="${html(id)}">Edit</button>` : '<span class="card-chevron" aria-hidden="true">›</span>'}</div><p class="team-mobile-hint">Tap to view lineup</p>${roster.length ? `<ul class="team-roster">${roster.map((member) => `<li><span>${html(member.name)}</span><small>${html(member.role)}</small></li>`).join('')}</ul>` : `<p class="sub">${html(emptyMessage)}</p>`}${footerHtml}</article>`;
}

export function teamDetail({ manager, name, roster, imageFor }) {
  return `<div class="team-detail-head"><div><p class="eyebrow">${html(manager)}</p><h2>${html(name)}</h2><p class="sub">Current roster</p></div></div>${roster.length ? `<div class="team-detail-grid">${roster.map((member) => `<article class="team-detail-member" data-team-cast-detail="${html(member.id)}" tabindex="0" role="button" aria-label="View ${html(member.name)} profile"><img src="${html(imageFor(member))}" style="object-position:${imagePosition(member.image_position)}% center" alt=""><div><b>${html(member.name)}</b><span>${html(member.displayRole || member.role)}</span></div><i aria-hidden="true">›</i></article>`).join('')}</div>` : '<p class="sub">No cast members assigned yet.</p>'}`;
}

export function castRosterRow({ id, name, roleDetails, roleDetailsHtml, image, position = 50, editButton = false }) {
  return `<div class="row cast-roster-row" data-cast-detail="${html(id)}" tabindex="0" role="button" aria-label="View ${html(name)} profile"><img class="player-photo" style="object-position:${imagePosition(position)}% center" src="${html(image)}" alt=""><span><b>${html(name)}</b><small>${roleDetailsHtml ?? html(roleDetails)}</small></span>${editButton ? `<button data-player-id="${html(id)}">Edit</button>` : '<span class="row-chevron" aria-hidden="true">›</span>'}</div>`;
}

export function danceCard({ id, kind, title, danceType, song, scores, castNames, scoreImage, pending = false, editButton = false }) {
  return `<article class="card dance-row dance-${html(kind)}" data-dance-detail="${html(id)}" tabindex="0" role="button" aria-label="View details for ${html(title)}"><div class="dance-card-top"><div class="dance-card-info"><p class="eyebrow">${kind === 'competitive' ? 'Competitive dance' : 'Performance'}</p><h3>${html(title)}</h3></div>${editButton ? `<button class="secondary" data-edit-dance="${html(id)}">Edit</button>` : '<span class="card-chevron" aria-hidden="true">›</span>'}</div>${kind === 'competitive' ? `<div class="dance-details"><span>${html(danceType || 'Dance type not set')}</span>${song ? `<span>${html(song)}</span>` : ''}</div><div class="judge-paddles" aria-label="Judge scores">${scores.map((score) => `<img src="${html(scoreImage(score.score))}" alt="${html(score.judge_name)}: ${Number(score.score)}">`).join('')}${pending ? `<span class="dance-score-pending">${scores.length ? `${scores.length} judge scores entered` : 'Awaiting scores'}</span>` : ''}</div>` : ''}${castNames.length ? `<div class="dance-cast" title="${html(castNames.join(', '))}"><span>Cast</span>${castNames.slice(0, 3).map((name) => `<b>${html(name)}</b>`).join('')}${castNames.length > 3 ? `<b>+${castNames.length - 3}</b>` : ''}</div>` : ''}</article>`;
}

export function teamPage({ weekHistory, total, period, rosterRows, available, availableMarkup, tradesMarkup = '<section id="tradeCenter" class="trade-center card"><div class="trade-center-loading">Loading trades…</div></section>' }) {
  return `<section class="card public-team-detail"><div class="team-summary-strip"><div class="team-history-strip">${weekHistory || '<p class="sub">Weekly history will appear after scoring begins.</p>'}</div><div class="league-detail-total"><strong>${total}</strong><span>${period} points</span></div></div><div class="public-team-columns"><section><div class="public-section-head"><div><p class="eyebrow">Scoring</p><h3>Team Roster</h3></div></div>${rosterRows}</section><div class="team-side-column"><section class="available-cast-panel"><div class="public-section-head"><div><p class="eyebrow">Free agents</p><h3>Available Cast</h3></div><span>${available} available</span></div><p class="sub">Cast members not currently assigned to a fantasy team.</p><div class="league-cast-grid available-grid">${availableMarkup || '<div class="empty compact-empty">Every cast member is currently assigned.</div>'}</div></section>${tradesMarkup}</div></div></section>`;
}

export function roleRatesTable(rates) {
  const order = ['Star', 'Pro', 'Eliminated Star', 'Eliminated Pro', 'Troupe', 'DWTS Next Pro', 'Hough', 'Judges + Hosts', 'Surprise'];
  const label = (name) => ({ 'Eliminated Star': 'Elim Star', 'Eliminated Pro': 'Elim Pro',
    'DWTS Next Pro': 'Next Pro', 'Judges + Hosts': 'Judge / Host' })[name] || name;
  const sorted = [...rates].sort((a, b) => order.indexOf(a.name) - order.indexOf(b.name) || a.name.localeCompare(b.name));
  return `<div class="card role-rate-table"><div class="role-rate-heading"><span>Cast role</span><span>Appearance points</span></div>${sorted.map((rate) => `<div class="role-rate-row"><span>${html(label(rate.name))}${rate.name === 'Surprise' ? ' *' : ''}</span><strong>${rate.name === 'Surprise' || rate.appearance_points == null ? 'Varies' : `+${Number(rate.appearance_points) || 0}`}</strong></div>`).join('')}</div><p class="surprise-rate-note">* Surprise cast is added as seen on the show. Its custom rate is set on that cast member.</p>`;
}

export function castProfile({ member, image, role, partner, teamName, fantasyPoints, judgesTotal,
  appearanceCount, showJudges, showWins, details = [], backLabel = '' }) {
  const firstName = String(member.name || '').split(' ')[0];
  return `${backLabel ? `<button class="profile-back-button secondary" id="profileBack" type="button">← Back to ${html(backLabel)}</button>` : ''}<div class="cast-profile-hero"><img src="${html(image)}" style="object-position:${imagePosition(member.image_position)}% center" alt="${html(member.name)}"><div><p class="eyebrow">${html(role)}</p><h2>${html(member.name)}</h2><p class="sub">${partner ? `Partnered with ${html(partner)}` : 'Current season cast'}</p><span class="cast-team-pill">${html(teamName || 'Available cast')}</span></div></div><div class="cast-profile-stats"><div><strong>${fantasyPoints || 0}</strong><span>Fantasy points</span></div>${showJudges ? `<div><strong>${judgesTotal || 0}</strong><span>Judges total</span></div>` : ''}<div><strong>${appearanceCount || 0}</strong><span>Appearances</span></div>${showWins ? `<div><strong>${Number(member.mirrorball_wins) || 0}</strong><span>Past wins</span></div>` : ''}</div><section class="cast-profile-copy"><h3>About ${html(firstName)}</h3><p>${html(member.bio || 'Biography details have not been added yet.')}</p>${member.career_highlights ? `<h3>Career highlights</h3><p>${html(member.career_highlights)}</p>` : ''}</section>${details.length ? `<div class="cast-profile-details">${details.map(([label, value]) => `<div><small>${html(String(label).replaceAll('_', ' '))}</small><strong>${html(value)}</strong></div>`).join('')}</div>` : ''}`;
}

export function danceDetail({ kind, title, danceType, song, scores, scoreImage, teams, castRows, imageFor }) {
  const total = scores.reduce((sum, score) => sum + Number(score.score || 0), 0);
  const best = teams[0]?.points || 0;
  const leaders = best ? teams.filter((team) => team.points === best).map((team) => team.name) : [];
  return `<div class="dance-detail-head"><p class="eyebrow">${kind === 'competitive' ? 'Competitive dance' : 'Performance'}</p><h2>${html(title)}</h2>${kind === 'competitive' ? `<p class="sub">${html(danceType || 'Dance type not set')}${song ? ` · ${html(song)}` : ''}</p>` : ''}</div>${kind === 'competitive' ? `<section class="detail-section dance-score-section"><div class="detail-section-title"><h3>Judges’ scores</h3><strong>${total || '—'}</strong></div><div class="detail-judges">${scores.map((score) => `<div><img src="${html(scoreImage(score.score))}" alt="${html(score.judge_name)}: ${Number(score.score)}"><span>${html(score.judge_name)}</span></div>`).join('') || '<p class="sub">No scores entered.</p>'}</div></section>` : ''}${castRows.length ? `<section class="dance-team-spotlight"><span>Top fantasy team${leaders.length === 1 ? '' : 's'}</span><strong>${html(leaders.join(' & ') || 'No points recorded')}</strong><small>${best ? `${best} point${best === 1 ? '' : 's'} earned from this dance` : 'Fantasy impact will appear when scoring is available.'}</small></section>` : ''}<section class="detail-section"><div class="detail-section-title"><h3>Cast & fantasy impact</h3>${castRows.length ? `<span>${castRows.length} cast member${castRows.length === 1 ? '' : 's'}</span>` : ''}</div>${castRows.length ? `<div class="dance-cast-impact-list">${castRows.map((row) => `<button type="button" data-dance-cast-profile="${html(row.member.id)}"><img src="${html(imageFor(row.member))}" style="object-position:${imagePosition(row.member.image_position)}% center" alt=""><span><b>${html(row.member.name)}</b><small>${html(row.role)} · ${html(row.teamName)}</small></span><strong>${row.points ? `+${row.points}` : '—'}</strong><i aria-hidden="true">›</i></button>`).join('')}</div>` : '<p class="sub">No cast appearances were recorded for this dance.</p>'}</section>`;
}
